### ISSUE TITLE
smoke tests should honor apps_domain for app creation

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/cf-smoke-tests#10]
Currently, when the smoke tests create apps, they appear to be getting created in the default domain for CF. When the tests go to query + make sure the app was created successfully, it uses the `smoke_tests.apps_domain` property. If this does not match the default CF domain, the tests will fail.

Tests should be updated so that app creation specifies the domain as well.

**Comment by DanLavine** [comment]
Hi @geofffranks,

We just pushed a [commit](https://github.com/cloudfoundry/cf-smoke-tests/commit/4ea03845eeb5237bc5630926356ea223436a28dd) which should address your issue. When pushing an application it will use the `apps_domain` property.

Thanks,
@DanLavine, CF OSS Release Integration Team

**Comment by Amit-PivotalLabs** [comment]
I believe this is now done, closing.
