### ISSUE TITLE
License/Notice file missing

### ISSUE THREAD

**Issue by aarondl** [cloudfoundry/cf-smoke-tests#12]
This repository has no LICENSE/NOTICE file. The other submodules in cf-release all (that I've seen) have one and are all making their dependencies' licenses visible in such a file. Notably the "COPYING" file from [gouuid](https://github.com/cloudfoundry/cf-smoke-tests/blob/master/Godeps/_workspace/src/github.com/nu7hatch/gouuid/COPYING) is missing.

**Comment by robdimsdale** [comment]
We have add commits https://github.com/cloudfoundry/cf-smoke-tests/commit/e3b65526a64f27cb5a2dabdd25d5e254cefd7206 and https://github.com/cloudfoundry/cf-smoke-tests/commit/f366a4cf6b73a5f05cba9bf4549dfb1e0ec3b25c which should address this issue.

We will close this now - feel free to open a new issue if you have any further issues or questions.

Rob & @zaksoup
