### ISSUE TITLE
Moving to GVT breaks production smoke tests

### ISSUE THREAD

**Issue by supertopher** [cloudfoundry/cf-smoke-tests#20]
[this commit here](https://github.com/cloudfoundry/cf-smoke-tests/commit/832f8e3ab924a1e6498d1d39be173f8e7ad81d80) breaks the pivotal production smoke tests.  I'm interested in what advantages we get from using GVT and how we can make this a world we all want to live in. 

I have reverted this commit so we can see if production is dead or not in the interim

thanks!

-- Topher

**Comment by Amit-PivotalLabs** [comment]
@supertopher 

What version of go do you have where you're running the smoke tests?  What is the exact failure message you're seeing?

**Comment by jaresty** [comment]
How did it break?  In that commit specifically there was an updated dependency that broke a test; we fixed it in [this commit](https://github.com/cloudfoundry/cf-smoke-tests/commit/ac9586bac8ae1534aa8cc7403b7acc3c708a6b04) a minute or two later.

**Comment by Amit-PivotalLabs** [comment]
We will be switching to gvt at some point.  This will move all the dependencies into `vendor`, which newer versions of Go (1.6+) will support out of the box.

We will likely *not* be switching the curl fail logic any time soon.

Since both commits were reverted and your issue is no longer happening, I will close this issue.  In the future please do not revert these types of commits.  I've restricted write-access to this repository to open source teams only.

**Comment by supertopher** [comment]
@jaresty the broken tests continued to be broken on prod with that patch you applied.  

@Amit-PivotalLabs The tests failed origionally using go `1.6` and later go `1.7` when i assumed go versions were probably the difference and updated concourse to be on `1.7` same error both times.  

the error as seen from our concourse is:

```
can't load package: package github.com/onsi/ginkgo/ginkgo: cannot find package "github.com/onsi/ginkgo/ginkgo" in any of:
	/tmp/build/a94a8fe5/go-lang/src/github.com/onsi/ginkgo/ginkgo (from $GOROOT)
	/tmp/build/a94a8fe5/cf-smoke-tests/Godeps/_workspace/src/github.com/onsi/ginkgo/ginkgo (from $GOPATH)
	/tmp/build/a94a8fe5/go-path/src/github.com/onsi/ginkgo/ginkgo
```

[this build](https://concourse.lakitu.cf-app.com/teams/main/pipelines/smoke-test:all-smoke-tests/jobs/cf_smoke_tests_production/builds/9176) if you have access to my concourse is an example.  The 15 builds before that all fail in a similar fashion.

**Comment by jaresty** [comment]
I don't have access, but @Amit-PivotalLabs might.  The $GOPATH from your
stack trace looks suspicious to me.  Are you setting it to
/tmp/build/a94a8fe5/cf-smoke-tests/Godeps/_workspace/ in CI?
