### ISSUE TITLE
Remove note about Godeps from README.md

### ISSUE THREAD

**Issue by jim80net** [cloudfoundry/cf-smoke-tests#21]
The README has the following note about running the tests:

> All go dependencies required by the smoke tests are vendored in cf-smoke-tests/Godeps. The test script itself, bin/test, ensures that the vendored dependencies are available when executing the tests by prepending this directory to $GOPATH.

However, Godeps is no longer used to vendor cf-smoke-tests dependencies. Perhaps this should be updated to a note about the `vendor` directory?

**Comment by supertopher** [comment]
@dsabeti can we close this issue?

**Comment by dsabeti** [comment]
Yup. Thanks @jim80net and @supertopher.
