### ISSUE TITLE
Running on bosh-lite errors when checking space guid

### ISSUE THREAD

**Issue by bonzofenix** [cloudfoundry/cf-smoke-tests#27]
We are running into a failure while deploying CF using the `cf-smoke-tests-release#17`. 

Error output:

```
[2017-04-05 14:41:58.57 (UTC)]> cf space cf_smoke_tests_space --guid
FAILED
No org targeted, use 'cf target -o ORG' to target an org.
```

The stack trace references to the following files:

https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/helpers.go#L56
https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/etcd_cluster_check/init_test.go#L76

@bonzofenix && @cloud-dude

**Comment by dsabeti** [comment]
Hey @bonzofenix. Could you show the full failure output? My suspicion is that some other part of the test is failing and preventing the test from targeting an org.

**Comment by bonzofenix** [comment]
Hi dsabeti,
Here is the complete output of the test: https://gist.github.com/bonzofenix/476fa832cae21d2a2fe2705b4fe5922e 
Thank you

**Comment by dsabeti** [comment]
The output suggests that the test timed out setting the quota on the organization. The very next command that would have run (if `cf set-quota` had succeeded) is `cf target`. It seems pretty clear that the failure to set the quota is the real failure, and the failure to fetch the space guid is a side-effect.

**Comment by bonzofenix** [comment]
cf_dial_timeout_in_seconds is set 300. Seems like a good amount of time. We looked through the code and it seems that the timeout is hardcoded: https://github.com/cloudfoundry/cf-smoke-tests/search?utf8=%E2%9C%93&q=DEFAULT_TIMEOUT&type=

**Comment by dsabeti** [comment]
Yeah, I don't know that opening the timeout will help. Have you tried running `cf set-quota` by hand? How long does it take? If it sometimes exceeds 30 seconds, you'll need to figure out why it takes so long. Somethings to consider:
- Is there something going wrong with your network? 
- Is the Cloud Controller experiencing significant load or facing resource limits? 
- Does the CC database respond to SQL commands in a reasonable amount of time?

**Comment by bonzofenix** [comment]
Ok you are right I see whats happening, seems that the [30 seconds timeout](https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/runtime/init_test.go#L63) is not enough:
<img width="1296" alt="screen shot 2017-04-07 at 11 30 40 am" src="https://cloud.githubusercontent.com/assets/317403/24810126/d835e1d0-1b86-11e7-9190-d469255b16e8.png">


Can we make this constant configurable?
Do you know how I could make my CF bosh-lite deployment run faster so that the smoke test would go green consistently?

**Comment by dsabeti** [comment]
@bonzofenix We can make that timeout configurable, but 30 seconds is pretty bad for a simple API call. In my comment above, I specified a few things to take a look at (CC load, CCDB slowness). 

You might also compare it to other CC endpoints. For example, does `cf curl /v2/info` take a long time? If so, there's something pretty bad going on with either your network or the CC.

For networking slowness, I'd suggest debugging with traceroute or tcpdump.

**Comment by dsabeti** [comment]
Hey @bonzofenix, any update on this?

**Comment by dsabeti** [comment]
I'm going to close the issue due to inactivity, but feel free to re-open it if you have more questions.
