### ISSUE TITLE
Any appetite for an app-autoscaler smoke test?

### ISSUE THREAD

**Issue by clhynfield** [cloudfoundry/cf-smoke-tests#34]
While waiting for a [potential SLI/SLO dashboard for PCF](https://github.com/cloudfoundry/cf-smoke-tests/pull/29#issuecomment-301945661), I wrote a [smoke test for App Autoscaler](https://github.com/clhynfield/cf-smoke-tests/tree/autoscaler-test/smoke/autoscaler) (a component much too fragile to meet my consumers' current service level expectations). Any interest in a pull request, or should I maintain my own fork? 

Thanks!
–c

**Comment by dsabeti** [comment]
Hey @clhynfield. Thanks for opening this issue. I'm happy to discuss adding new tests here.

First, are you talking about [this autoscaling project](https://github.com/cloudfoundry-incubator/app-autoscaler)? I just want to make sure we're discussing the same project.

Like we discussed the issue that you linked to, smoke tests is supposed to be a test suite for validating a deployment after finishing a `bosh deploy`. Another way to think about it is that it's a test that validates your deployment configuration.

It sounds like you want to use this test instead to validate the ongoing availability of the autoscaler. Am I understanding that right?

It also seems like that project still hasn't achieved MVP yet. I'm not sure if it makes sense to add a test for a feature that's still being incubated.

**Comment by dsabeti** [comment]
Hi @clhynfield, any updates on this? I'd definitely be interested to discuss further.

**Comment by clhynfield** [comment]
Sorry to leave you hanging, @dsabeti! I'm interested in testing the [app autoscaler that ships with Pivotal Cloud Foundry](https://docs.pivotal.io/pivotalcf/1-11/appsman-services/autoscaler/using-autoscaler.html) and that's available on the PWS Marketplace. I had assumed the API and back-end were the [app autoscaler](https://github.com/cloudfoundry-incubator/app-autoscaler) project you linked to, but as I look at it, I'm not sure the Pivotal product is related to any open source project.

**Comment by dsabeti** [comment]
No worries!

I'm glad I asked which project you were looking at. If it has to do with specific vendor's product (in this case, Pivotal), we shouldn't add a test to smoke-tests for it. If the OSS autoscaler moves out of incubation toward being an out-of-the-box feature of Cloud Foundry, I'd probably be interested in adding such a test.

**Comment by dsabeti** [comment]
@clhynfield, do you feel ok closing this issue? The plan is not move forward with any new smoke tests right now.

**Comment by clhynfield** [comment]
Agreed. Thanks for the convo, @dsabeti!
