### ISSUE TITLE
Bump cf-test-helpers

### ISSUE THREAD

**Issue by forbushbl** [cloudfoundry/cf-smoke-tests#38]
Please bump to cf-test-helpers commit 1a8c223f1cc4110cc866f7298ff622b83e274173 or later.

The version of cf-test-helpers that is currently referenced has a bug where even though an existing user is specified it still creates a user. If UAA is backed by LDAP, then this results in two users with the same username but with different origins. The commit of cf-test-helpers that resolves this issue is --> https://github.com/cloudfoundry-incubator/cf-test-helpers/commit/1a8c223f1cc4110cc866f7298ff622b83e274173

**Comment by dsabeti** [comment]
Hi @forbushbl. Thanks for the nudge. I just bumped it this repo. It's making it's way through our testing pipelines, so we'll hopefully ship a new release of cf-smoke-tests-release soon.

**Comment by dsabeti** [comment]
Hi @forbushbl, sorry for failing to follow up on this. cf-smoke-tests has the latest commit of cf-test-helpers now. I'll close this issue.
