### ISSUE TITLE
Test applications use http URLs - which may not be available

### ISSUE THREAD

**Issue by james-masson** [cloudfoundry/cf-smoke-tests#4]
A PCF customer chooses to not allow HTTP traffic to his application domains.

https://github.com/cloudfoundry-incubator/cf-smoke-tests/blob/master/smoke/runtime_test.go#L30

The embedded PCF smoke tests always use HTTP to check the status of the test applications, and hence smoke tests fail in this environment. The environment is otherwise perfectly functional.

**Comment by dieucao** [comment]
This change to cf-smoke-tests has been merged.
