### ISSUE TITLE
smoke tests failures when http is disabled

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry/cf-smoke-tests#48]
Hi,

I'm running into some failures after disabling http listener on gorouters ([router.disable_http](https://github.com/cloudfoundry/routing-release/blob/develop/jobs/gorouter/spec#L86) set to true for routing-release).

The errors occurs on **RoutingIsolationSegments** tests. 

From my understanding, the following function has **http** scheme hard-coded which leads the test to a failure since port 80 is not reachable.

 https://github.com/cloudfoundry/cf-smoke-tests/blob/e260f73b675b9225e299384ab6c9e889743de80c/smoke/isolation_segments/v3_helpers.go#L117-L124

* Q: is there another way to run smoke-tests with a disabled http port ?
* Q: if not, would you accept a PR that allows such a use-case ?
* Q: if yes, what would be the best approach ?
   1. forcing **https** scheme in the function as it already is in [runtime_test.go](https://github.com/cloudfoundry/cf-smoke-tests/blob/master/smoke/runtime/runtime_test.go#L33)
   2. adding a configuration key **disable_http** in **integration_config.json** and creating the url accordingly ? This will require to add a new *spec* entry in [cloudfoundry/cf-smoke-tests-release](https://github.com/cloudfoundry/cf-smoke-tests-release)

**Comment by davewalter** [comment]
Hi @psycofdj,

This has been recently changed to use https via this PR https://github.com/cloudfoundry/cf-smoke-tests/pull/52 so this should no longer be an issue. Please feel free to re-open if you are still having problems.

Regards,
Dave and @Changdrew
