### ISSUE TITLE
Missing method in smoke.config

### ISSUE THREAD

**Issue by richardg0510** [cloudfoundry/cf-smoke-tests#49]
After the latest commit, the following error is encountered when running ./bin/test

`# github.com/cloudfoundry/cf-smoke-tests/smoke/isolation_segments [github.com/cloudfoundry/cf-smoke-tests/smoke/isolation_segments.test]
smoke/isolation_segments/init_test.go:22:52: cannot use testConfig (type *smoke.Config) as type workflowhelpers.testSuiteConfig in argument to workflowhelpers.NewSmokeTestSuiteSetup:
	*smoke.Config does not implement workflowhelpers.testSuiteConfig (missing GetAddExistingUserToExistingSpace method)`

**Comment by vitreuz** [comment]
Fixed in 3ffa89ee and 8f6d7508
