### ISSUE TITLE
Empty logging application name

### ISSUE THREAD

**Issue by psycofdj** [cloudfoundry/cf-smoke-tests#54]
Hello, 

When running smoke tests with pre-defined logging app name in configuration, the configuration entry is not used and tests are ran with an empty app name.

I'm afraid that the variable `appName` is never assigned in that use-case. It should take the value of `testConfig.LoggingApp`

https://github.com/cloudfoundry/cf-smoke-tests/blob/f75443b6e6e03a2fcdf91dfe2c0a16bbbdf2dba7/smoke/logging/loggregator_test.go#L16-L35

**Comment by Changdrew** [comment]
Hi @psycofdj!

Thanks for the heads up. This should have been fixed with this commit ed929c0f855cfcdf2c70ce7184b30f615927ec85

Cheers,
Andrew
