### ISSUE TITLE
Try to run cf-smoke-test from Ubuntu : getting panic: /tmp/ginkgo820229353/isolation_segments.test flag redefined: ginkgo.seed

### ISSUE THREAD

**Issue by mukulk2020** [cloudfoundry/cf-smoke-tests#60]
[Error-cf-smoke-test.docx](https://github.com/cloudfoundry/cf-smoke-tests/files/4465934/Error-cf-smoke-test.docx)
Attaching the screenshot for more information . PLease check and resolve asap.

**Comment by acosta11** [comment]
Hello,

I don't recall having seen this issue in any of our CI environments running smoke tests, but when searching for the phrase "flag redefined: ginkgo.seed", I found a few ginkgo issues that indicate this may be a golang vendoring issue: [ginkgo #234](https://github.com/onsi/ginkgo/issues/234#issuecomment-196645747) and [ginkgo #285](https://github.com/onsi/ginkgo/issues/285). Does the problem persist after following the gopath and vendoring guidance in these issues?

Thanks,
Andrew
