### ISSUE TITLE
cf push in runtime_tests uses random domain and can fail

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry/cf-smoke-tests#64]
Hi everyone,

with this change you've made the cf-smoke-tests compliant with CF CLI v7: https://github.com/cloudfoundry/cf-smoke-tests/commit/746b4a16d2047a78def2b3454de43e040c4bbf5f#diff-86a47d06f5bb2981fa07be2b09b571df

For the "isolation_segments" test there is now an app manifest with a route. But for the "runtime_test" there is no manifest and the "-d" option has been removed. In our landscapes, the runtime test now fails because it picks the first domain from the "cf domains" list which is not usable. Instead, the test should use a manifest which specifies a route that points to the "apps_domain".

Can you please fix that?

Thanks and Best Regards,

  Jochen.

**Comment by jamespollard8** [comment]
Fixed by 5a65b335eb5feae92731c8470e62a648bd00c186 (thanks @ericpromislow for the fix and to @jochenehret for the report)
