### ISSUE TITLE
Support for go modules in cf smoke tests

### ISSUE THREAD

**Issue by davfarre** [cloudfoundry/cf-smoke-tests#65]
It looks like cf-smoke-tests does not use go modules and instead uses module management using a legacy GOPATH mode.
FYI this will prevent future versions of go from working with cf-smoke-tests. We noticed this problem when bumping go to `1.16` and worked around the issue by setting :
`go env -w GO111MODULE=auto` but this will not work once go 1.17 is out.

Are there plans to update cf-smoke-tests? I also notice alot of the dependencies have older versions that need updating?

**Comment by ctlong** [comment]
This was completed as of https://github.com/cloudfoundry/cf-smoke-tests/commit/0fab4e9fd465a60f7cbf07280fcf2126651aac08.
